addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.22.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.12")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"               % "1.1.6")
addSbtPlugin("ch.epfl.scala"      % "sbt-tasty-mima"                % "1.4.0")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-site"            % "0.8.7")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"                 % "2.4.2")
